blank_issues_enabled: false
contact_links:
  - name: Have a question?
    url: https://github.com/GraphQL-Portal/graphql-portal/discussions/new
    about: Ask us a questions is your not sure how to proceed, have some suggestions or questions.
