name: Documentation Website Deployment
on:
  push:
    paths:
      - 'docs-website/**'
  workflow_dispatch:

jobs:
  deploy-website:
    name: Deploy Documentation site
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node@14.x
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Get Yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-14-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-14-yarn-

      - name: Install dependencies
        run: cd docs-website && yarn install

      - name: Build docs
        run: yarn docs:build

      - name: Configure Git Credentials
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          echo "machine github.com login ${{github.actor}} password ${{secrets.GITHUB_TOKEN}}" > ~/.netrc

      - name: Deploy docs
        run: yarn docs:deploy
        env:
          GIT_USER: ${{github.actor}}
